baseURL = 'https://kkarol01.github.io/'
locale = 'en-us'
title = "Karol's Blog"
theme = 'ananke'

[params]
  mainSections = ['posts']
  recent_posts_number = 3

[caches]
  [caches.images]
    dir = ':cacheDir/images'